FROM node:12
WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
RUN yarn install --production=true
COPY ./src ./src
COPY ./.env.production ./.env.production
COPY ./ormconfig.ts ./ormconfig.ts
COPY ./nodemon.json ./nodemon.json
COPY ./tsconfig.json ./tsconfig.json
EXPOSE 80
CMD [ "yarn", "run", "setup:prod", "&&", "yarn", "run", "prod"]