FROM node:12
WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY ./src ./src
COPY ./deployment ./deployment
COPY ./.env.production ./.env.production
COPY ./.env.example ./.env.example
COPY ./ormconfig.ts ./ormconfig.ts
COPY ./nodemon.json ./nodemon.json
COPY ./tsconfig.json ./tsconfig.json
EXPOSE 80
RUN yarn install --production=true
RUN yarn run build
CMD yarn run prod